/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Certification {
  'date' : string,
  'name' : string,
  'issuer' : string,
}
export interface CodingAchievement {
  'rank' : string,
  'platform' : string,
  'score' : bigint,
}
export interface Education {
  'field' : string,
  'startYear' : bigint,
  'endYear' : bigint,
  'institution' : string,
  'degree' : string,
}
export interface Experience {
  'endDate' : [] | [string],
  'role' : string,
  'description' : string,
  'company' : string,
  'startDate' : string,
}
export interface PersonalInfo {
  'linkedin' : string,
  'title' : string,
  'name' : string,
  'email' : string,
  'website' : string,
  'phone' : string,
  'location' : string,
  'github' : string,
}
export interface Project {
  'link' : string,
  'name' : string,
  'description' : string,
  'technologies' : Array<string>,
}
export interface Skill {
  'name' : string,
  'level' : bigint,
  'category' : string,
}
export interface _SERVICE {
  'getCertifications' : ActorMethod<[], Array<Certification>>,
  'getCodingAchievements' : ActorMethod<[], Array<CodingAchievement>>,
  'getEducation' : ActorMethod<[], Array<Education>>,
  'getExperiences' : ActorMethod<[], Array<Experience>>,
  'getPersonalInfo' : ActorMethod<[], PersonalInfo>,
  'getProjects' : ActorMethod<[], Array<Project>>,
  'getSkills' : ActorMethod<[], Array<Skill>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];