/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Certification = IDL.Record({
  'date' : IDL.Text,
  'name' : IDL.Text,
  'issuer' : IDL.Text,
});
export const CodingAchievement = IDL.Record({
  'rank' : IDL.Text,
  'platform' : IDL.Text,
  'score' : IDL.Nat,
});
export const Education = IDL.Record({
  'field' : IDL.Text,
  'startYear' : IDL.Nat,
  'endYear' : IDL.Nat,
  'institution' : IDL.Text,
  'degree' : IDL.Text,
});
export const Experience = IDL.Record({
  'endDate' : IDL.Opt(IDL.Text),
  'role' : IDL.Text,
  'description' : IDL.Text,
  'company' : IDL.Text,
  'startDate' : IDL.Text,
});
export const PersonalInfo = IDL.Record({
  'linkedin' : IDL.Text,
  'title' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'website' : IDL.Text,
  'phone' : IDL.Text,
  'location' : IDL.Text,
  'github' : IDL.Text,
});
export const Project = IDL.Record({
  'link' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'technologies' : IDL.Vec(IDL.Text),
});
export const Skill = IDL.Record({
  'name' : IDL.Text,
  'level' : IDL.Nat,
  'category' : IDL.Text,
});

export const idlService = IDL.Service({
  'getCertifications' : IDL.Func([], [IDL.Vec(Certification)], ['query']),
  'getCodingAchievements' : IDL.Func(
      [],
      [IDL.Vec(CodingAchievement)],
      ['query'],
    ),
  'getEducation' : IDL.Func([], [IDL.Vec(Education)], ['query']),
  'getExperiences' : IDL.Func([], [IDL.Vec(Experience)], ['query']),
  'getPersonalInfo' : IDL.Func([], [PersonalInfo], ['query']),
  'getProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'getSkills' : IDL.Func([], [IDL.Vec(Skill)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Certification = IDL.Record({
    'date' : IDL.Text,
    'name' : IDL.Text,
    'issuer' : IDL.Text,
  });
  const CodingAchievement = IDL.Record({
    'rank' : IDL.Text,
    'platform' : IDL.Text,
    'score' : IDL.Nat,
  });
  const Education = IDL.Record({
    'field' : IDL.Text,
    'startYear' : IDL.Nat,
    'endYear' : IDL.Nat,
    'institution' : IDL.Text,
    'degree' : IDL.Text,
  });
  const Experience = IDL.Record({
    'endDate' : IDL.Opt(IDL.Text),
    'role' : IDL.Text,
    'description' : IDL.Text,
    'company' : IDL.Text,
    'startDate' : IDL.Text,
  });
  const PersonalInfo = IDL.Record({
    'linkedin' : IDL.Text,
    'title' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'website' : IDL.Text,
    'phone' : IDL.Text,
    'location' : IDL.Text,
    'github' : IDL.Text,
  });
  const Project = IDL.Record({
    'link' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'technologies' : IDL.Vec(IDL.Text),
  });
  const Skill = IDL.Record({
    'name' : IDL.Text,
    'level' : IDL.Nat,
    'category' : IDL.Text,
  });
  
  return IDL.Service({
    'getCertifications' : IDL.Func([], [IDL.Vec(Certification)], ['query']),
    'getCodingAchievements' : IDL.Func(
        [],
        [IDL.Vec(CodingAchievement)],
        ['query'],
      ),
    'getEducation' : IDL.Func([], [IDL.Vec(Education)], ['query']),
    'getExperiences' : IDL.Func([], [IDL.Vec(Experience)], ['query']),
    'getPersonalInfo' : IDL.Func([], [PersonalInfo], ['query']),
    'getProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'getSkills' : IDL.Func([], [IDL.Vec(Skill)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };